repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    -   id: clang-format
        exclude: '^(lib/bxzstr|cmake|lib/stb).*|.c$'
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args:
            - --profile=black
